services:
  application:
    image: httpd
    networks:
      - mynetwork

  nginx:
    image: nginx-basic-auth
    ports:
      - "80:80"
    depends_on:
      - application
    environment: 
      - FORWARD_HOST=application
      - FORWARD_PORT=80
      - BASIC_USERNAME=john.doe
      - BASIC_PASSWORD=myp@ssword!
    networks:
      - mynetwork

networks:
  mynetwork: